{
  "hash": "37e5713dc6dc03e747b3ea745b784f9d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Marker-QTL Unit Congruency\"\n---\n\n📐 **Theory:** [BayesA](../theory/bayes-bayesa.qmd) ·\n[BayesR](../theory/bayes-bayesr.qmd) ·\n[GBLUP](../theory/blup-gblup.qmd) ·\n[GWABLUP](../theory/blup-gwablup.qmd)\n\n## Objective\n\nWe developed a theory called the **Marker-QTL Unit Congruence Theory**, where:\n\n> *Genomic prediction accuracy is maximised when the marker unit is\n> aligned with the biological QTL unit.*\n\nIn other words, if the QTL effects actually live at the haplotype-block\nlevel, microhaplotype (MH) markers are expected to outperform\nsingle-SNP markers, and vice versa. To test this, we ran a proof-of-concept simulation under both QTL scenarios and compared four genomic prediction models across two marker representations.\n\n## Study design\n\nA forward simulation over a fully crossed grid.\n\n| Factor | Levels |\n|---|---|\n| **QTL scenario** | `QTL@SNP` (true genetic effects at single-SNP level), `QTL@MH` (effects at haplotype-block level) |\n| **Marker representation** | `SNP` (z-score encoding via `construct_snp_matrix(encoding=\"zscore\")`), `MH` (multi-allelic $\\mathbf{W}_{\\alpha h}$ coding, Da 2015, via `construct_wah_matrix`) |\n| **Model** | `BayesR`, `BayesA`, `GBLUP`, `GWABLUP` |\n| **Trait type** | Continuous, binary (threshold at the training-set liability median) |\n| **Total** | $2 \\times 2 \\times 4 \\times 2 = 32$ model fits |\n\n**Population parameters**: $n_{\\text{total}} = 300$ (training 200,\ntest 100), 50 haplotype blocks × 2 SNPs/block = 100 SNPs total,\n10 QTL, target heritability $h^2 = 0.3$. SNP MAF $\\sim$ Unif(0.1,\n0.5). In both scenarios the microhaplotype matrix is derived from the\nsame SNP data via phasing and $\\mathbf{W}_{\\alpha h}$ encoding, so any difference in performance reflects the marker representation alone, not the\nunderlying genotypes.\n\nWe ran MCMC for 20,000 iterations with a 10,000 burn-in, thinning every 10 samples, and seed 123.\nPrior hyperparameters follow the `masbayes` defaults, where for BayesA\n($\\nu = 4.5$) and BayesR\n($\\pi = (0.90,\\, 0.05,\\, 0.03,\\, 0.02)$,\n$\\text{variance\\_class} = (0,\\, 0.01,\\, 0.1,\\, 1)$).\n\n## Metrics and interpretation\n\nLet $\\hat{u}_i = \\widehat{\\text{GEBV}}_i$ for individual $i$,\n$y_i$ = observed phenotype, $g_i$ = true breeding value (TBV),\n$\\hat{z}_i$ = posterior mean liability (binary trait),\n$\\Phi(\\cdot)$ = standard normal CDF.\n\n| Metric | Formula | Range | Interpretation |\n|---|---|---|---|\n| $r_{\\text{train}}$ | $\\displaystyle r_{\\text{train}} = \\frac{\\mathrm{Cov}(\\hat{u},\\, y)}{\\sqrt{\\mathrm{Var}(\\hat{u})\\,\\mathrm{Var}(y)}}$ on the training set. For binary traits, replace $y$ with $\\hat{z}$. | $[-1,\\, 1]$ | Training fit. Closer to 1 is better, but values > 0.95 can signal overfitting. |\n| $r_{\\text{test},y}$ | $\\displaystyle r_{\\text{test},y} = \\frac{\\mathrm{Cov}(\\hat{u}_{\\text{test}},\\, y_{\\text{test}})}{\\sqrt{\\mathrm{Var}(\\hat{u}_{\\text{test}})\\,\\mathrm{Var}(y_{\\text{test}})}}$ | $[-1,\\, 1]$ | **Predictive ability** on held-out data. 1 = ideal. |\n| $r_{\\text{test},g}$ | $\\displaystyle r_{\\text{test},g} = \\frac{\\mathrm{Cov}(\\hat{u}_{\\text{test}},\\, g_{\\text{test}})}{\\sqrt{\\mathrm{Var}(\\hat{u}_{\\text{test}})\\,\\mathrm{Var}(g_{\\text{test}})}}$ | $[-1,\\, 1]$ | **Accuracy against TBV** — the primary metric, available only in simulation. Closer to 1 is better. |\n| bias | Continuous: slope $\\hat{b}$ of $y_i = a + b\\,\\hat{u}_i + \\varepsilon_i$, $\\displaystyle \\hat{b} = \\frac{\\mathrm{Cov}(\\hat{u},\\, y)}{\\mathrm{Var}(\\hat{u})}$. Binary: slope $\\hat{b}$ of $y_i = a + b\\,\\Phi(\\hat{u}_i) + \\varepsilon_i$. | around 1 | $\\hat{b} = 1$ is ideal; $\\hat{b} < 1$ indicates over-dispersion (predictions too extreme); $\\hat{b} > 1$ indicates under-dispersion (predictions too compressed). |\n| $\\hat{h}^2_{\\text{post}}$ | $\\displaystyle \\hat{h}^2_{\\text{post}} = \\frac{\\hat{\\sigma}^2_g}{\\hat{\\sigma}^2_g + \\hat{\\sigma}^2_e}$ with variance components taken from the posterior. | $[0,\\, 1]$ | Posterior heritability estimate. Compare with the target $h^2 = 0.3$. |\n| AUC | $\\displaystyle \\text{AUC} = \\Pr\\!\\left(\\hat{u}_i > \\hat{u}_j \\,\\middle|\\, y_i = 1,\\; y_j = 0\\right)$ | $[0.5,\\, 1]$ | **Binary only.** 0.5 = random, 1.0 = perfect. > 0.7 is good, > 0.9 is very good. Rank-invariant. |\n\n## Results\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show full R script\"}\nlibrary(masbayes)\nlibrary(masreml)\n\n# ── CONFIG ───────────────────────────────────────────────────────────────────\nconfig <- list(\n  seed            = 42,\n  n_total         = 300,\n  n_train         = 200,\n  n_test          = 100,\n  n_blocks        = 50,\n  n_snp_per_block = 2,\n  h2_target       = 0.3,\n  n_qtl           = 10,\n  mcmc = list(\n    n_iter = 20000L,\n    n_burn = 10000L,\n    n_thin = 10L,\n    seed   = 123L\n  ),\n  bayesr = list(\n    pi_vec         = c(0.90, 0.05, 0.03, 0.02),\n    variance_class = c(0, 0.01, 0.1, 1),\n    a0_e           = 5,\n    a0_g           = 5\n  ),\n  bayesa = list(\n    nu   = 4.5,\n    a0_e = 10\n  )\n)\n\nset.seed(config$seed)\nn_total         <- config$n_total\nn_train         <- config$n_train\nn_test          <- config$n_test\nn_blocks        <- config$n_blocks\nn_snp_per_block <- config$n_snp_per_block\nn_snp_total     <- n_blocks * n_snp_per_block\n\n# ── 1. Generate SNP genotype ─────────────────────────────────────────────────\nmaf <- runif(n_snp_total, 0.1, 0.5)\ngeno_snp_all <- matrix(0L, nrow = n_total, ncol = n_snp_total)\nfor (j in 1:n_snp_total)\n  geno_snp_all[, j] <- as.integer(rbinom(n_total, 2, maf[j]))\n\n# ── 2. Phase SNP -> haplotype ────────────────────────────────────────────────\nhap_all <- matrix(0L, nrow = n_total, ncol = n_snp_total * 2)\nfor (j in 1:n_snp_total) {\n  for (i in 1:n_total) {\n    g  <- geno_snp_all[i, j]\n    h1 <- if (g == 2) 1L else if (g == 0) 0L else as.integer(rbinom(1, 1, 0.5))\n    h2 <- as.integer(g - h1)\n    hap_all[i, 2*j-1] <- h1 + 1L\n    hap_all[i, 2*j  ] <- h2 + 1L\n  }\n}\nstorage.mode(hap_all) <- \"integer\"\n\n# ── 3. Reorder hap columns by block ─────────────────────────────────────────\nhap_cols_per_block <- n_snp_per_block * 2\nhap_reordered <- matrix(0L, nrow = n_total, ncol = n_snp_total * 2)\ncol_out <- 1\nfor (b in 1:n_blocks) {\n  for (j in ((b-1)*n_snp_per_block + 1):(b*n_snp_per_block)) {\n    hap_reordered[, col_out]   <- hap_all[, 2*j-1]\n    hap_reordered[, col_out+1] <- hap_all[, 2*j  ]\n    col_out <- col_out + 2\n  }\n}\nstorage.mode(hap_reordered) <- \"integer\"\n\n# ── 4. Encode MH per block ───────────────────────────────────────────────────\nidx_train <- 1:n_train\nidx_test  <- (n_train+1):n_total\n\nencode_hap <- function(mat)\n  apply(mat, 1, function(x) sum(x * 3^(seq_along(x)-1)))\n\nhap_block_all    <- matrix(0L, nrow = n_total, ncol = n_blocks * 2)\nallele_freq_list <- list(haplotype=c(), allele=c(), freq=c())\n\nfor (b in 1:n_blocks) {\n  cols    <- ((b-1)*hap_cols_per_block + 1):(b*hap_cols_per_block)\n  hap_sub <- hap_reordered[, cols]\n  h1_id   <- encode_hap(hap_sub[, seq(1, hap_cols_per_block, 2), drop=FALSE])\n  h2_id   <- encode_hap(hap_sub[, seq(2, hap_cols_per_block, 2), drop=FALSE])\n  hap_block_all[, 2*b-1] <- h1_id\n  hap_block_all[, 2*b  ] <- h2_id\n  tbl     <- table(c(h1_id[idx_train], h2_id[idx_train]))\n  freqs   <- as.numeric(tbl) / sum(tbl)\n  alleles <- as.integer(names(tbl))\n  allele_freq_list$haplotype <- c(allele_freq_list$haplotype,\n                                   rep(paste0(\"block_\", b), length(alleles)))\n  allele_freq_list$allele    <- c(allele_freq_list$allele, alleles)\n  allele_freq_list$freq      <- c(allele_freq_list$freq, freqs)\n}\nstorage.mode(hap_block_all) <- \"integer\"\ncolnames_block <- paste0(\"block_\", rep(1:n_blocks, each = 2))\n\n# ── 5. Construct W matrices ──────────────────────────────────────────────────\nwah_train  <- construct_wah_matrix(\n  hap_block_all[idx_train,], colnames_block, allele_freq_list, NULL, TRUE)\nW_mh_train <- wah_train$W_ah\nref_struct  <- list(allele_info=wah_train$allele_info,\n                    dropped_alleles=wah_train$dropped_alleles)\nW_mh_test  <- construct_wah_matrix(\n  hap_block_all[idx_test,], colnames_block, NULL, ref_struct, TRUE)$W_ah\n\nsnp_train_obj <- construct_snp_matrix(geno_snp_all[idx_train, ],\n                                      encoding = \"zscore\")\nW_snp_train   <- snp_train_obj$W\np_snp_tr      <- snp_train_obj$freq\nsd_snp_tr     <- snp_train_obj$sd\n\nW_snp_test    <- construct_snp_matrix(geno_snp_all[idx_test, ],\n                                      encoding = \"zscore\",\n                                      ref_freq = p_snp_tr,\n                                      ref_sd   = sd_snp_tr)$W\nW_snp_all     <- construct_snp_matrix(geno_snp_all,\n                                      encoding = \"zscore\",\n                                      ref_freq = p_snp_tr,\n                                      ref_sd   = sd_snp_tr)$W\nstorage.mode(W_snp_train) <- \"double\"\nstorage.mode(W_snp_test)  <- \"double\"\nstorage.mode(W_snp_all)   <- \"double\"\n\nwah_all    <- construct_wah_matrix(\n  hap_block_all, colnames_block, allele_freq_list, NULL, TRUE)\nW_mh_all   <- wah_all$W_ah\n\n# ── 6. Simulate y (continuous and binary) ───────────────────────────────────\nsimulate_y <- function(W_source, idx_tr, label, h2_target = 0.3,\n                       n_qtl = 10, type = \"snp\") {\n  n_col     <- ncol(W_source)\n  beta_true <- rep(0, n_col)\n  qtl_idx   <- sample(n_col, n_qtl)\n  if (type == \"snp\") {\n    raw <- rgamma(n_qtl, shape=0.4, scale=1) * sample(c(-1,1), n_qtl, replace=TRUE)\n    beta_true[qtl_idx] <- raw / sqrt(sum(raw^2))\n  } else {\n    raw <- rnorm(n_qtl)\n    beta_true[qtl_idx] <- raw / sqrt(sum(raw^2))\n  }\n  tbv_all  <- as.vector(W_source %*% beta_true)\n  tbv_mean <- mean(tbv_all[idx_tr])\n  tbv_sd   <- sd(tbv_all[idx_tr])\n  tbv_std  <- (tbv_all - tbv_mean) / tbv_sd\n  sg <- var(tbv_std[idx_tr])\n  se <- sg * (1 - h2_target) / h2_target\n  y_cont <- tbv_std + rnorm(length(tbv_std), 0, sqrt(se))\n  threshold <- median(y_cont[idx_tr])\n  y_bin  <- as.numeric(y_cont > threshold)\n  h2_obs <- sg / (sg + se)\n  list(y_cont=y_cont, y_bin=y_bin, g=tbv_std, sigma2_g=sg, sigma2_e=se, h2=h2_obs)\n}\n\nset.seed(config$seed)\nsc_snp <- simulate_y(W_snp_all, idx_train, \"QTL@SNP\",\n                     h2_target = config$h2_target,\n                     n_qtl     = config$n_qtl,\n                     type      = \"snp\")\nset.seed(config$seed)\nsc_mh  <- simulate_y(W_mh_all,  idx_train, \"QTL@MH\",\n                     h2_target = config$h2_target,\n                     n_qtl     = config$n_qtl,\n                     type      = \"mh\")\n\n# ── 7. Bayesian model fitting ────────────────────────────────────────────────\nmcmc_p <- config$mcmc\n\nrun_scenario <- function(sc, W_tr, W_te, y_tr, y_te, g_te,\n                         marker_label, trait_type = \"continuous\") {\n  y_train <- y_tr\n  y_test  <- y_te\n  resp    <- if (trait_type == \"binary\") \"binary\" else \"gaussian\"\n  mtype   <- if (identical(marker_label, \"SNP\")) \"snp\" else \"multiallelic\"\n  wtw     <- colSums(W_tr^2)\n  rows    <- list()\n  se_init <- if (trait_type == \"binary\") 1.0 else sc$sigma2_e\n  sg_init <- if (trait_type == \"binary\") 1.0 else sc$sigma2_g\n\n  for (model in c(\"BayesR\", \"BayesA\")) {\n    result <- tryCatch({\n      if (model == \"BayesR\") {\n        res <- run_bayesr(\n          w=W_tr, y=y_train, wtw_diag=wtw,\n          marker_type   = mtype,\n          pi_vec        = config$bayesr$pi_vec,\n          sigma2_e_init = se_init,\n          sigma2_ah     = sg_init,\n          prior_params  = list(\n            a0_e           = config$bayesr$a0_e,\n            a0_g           = config$bayesr$a0_g,\n            variance_class = config$bayesr$variance_class\n          ),\n          mcmc_params   = mcmc_p,\n          method        = \"mcmc\",\n          response_type = resp,\n          fold_id       = 0L)\n      } else {\n        res <- run_bayesa(\n          w=W_tr, y=y_train, wtw_diag=wtw,\n          marker_type   = mtype,\n          nu            = config$bayesa$nu,\n          sigma2_g      = sg_init,\n          sigma2_e_init = se_init,\n          prior_params  = list(a0_e = config$bayesa$a0_e),\n          mcmc_params   = mcmc_p,\n          method        = \"mcmc\",\n          response_type = resp,\n          fold_id       = 0L)\n      }\n\n      gebv_tr  <- res$GEBV\n      pred_te  <- predict(res, W_te, y_test)\n      gebv_te  <- pred_te$GEBV\n      r_test_y <- cor(gebv_te, y_test)\n      r_test_g <- cor(gebv_te, g_te)\n\n      if (trait_type == \"binary\" && !is.null(res$z_hat) && is.numeric(res$z_hat)) {\n        r_train       <- cor(gebv_tr, res$z_hat)\n        bias_test     <- pred_te$metrics$bias\n        sigma2_g_post <- var(gebv_tr)\n        h2_post       <- sigma2_g_post / (sigma2_g_post + 1.0)\n      } else {\n        r_train       <- cor(gebv_tr, y_train)\n        bias_test     <- pred_te$metrics$bias\n        sigma2_g_post <- var(gebv_tr)\n        sigma2_e_post <- mean(res$sigma2_e_samples)\n        h2_post       <- sigma2_g_post / (sigma2_g_post + sigma2_e_post)\n      }\n\n      auc <- if (trait_type == \"binary\") pred_te$metrics$AUC else NA\n\n      list(status=\"OK\", r_train=round(r_train,3),\n           r_test_y=round(r_test_y,3), r_test_g=round(r_test_g,3),\n           bias=round(bias_test,3), h2=round(h2_post,3),\n           auc=round(auc,3), p=ncol(W_tr))\n    }, error = function(e)\n      list(status=paste(\"ERROR:\", conditionMessage(e)),\n           r_train=NA, r_test_y=NA, r_test_g=NA,\n           bias=NA, h2=NA, auc=NA, p=ncol(W_tr)))\n\n    rows[[model]] <- data.frame(\n      Trait=trait_type, Marker=marker_label, Model=model,\n      Status=result$status, r_train=result$r_train,\n      r_test_y=result$r_test_y, r_test_g=result$r_test_g,\n      bias=result$bias, h2_post=result$h2, AUC=result$auc,\n      p=result$p, stringsAsFactors=FALSE)\n  }\n  do.call(rbind, rows)\n}\n\n# ── 7b. GBLUP via masreml ────────────────────────────────────────────────────\nrownames(geno_snp_all) <- as.character(1:n_total)\nG_snp_full <- build_G_snp(geno_snp_all, ref_W = geno_snp_all[idx_train, ])\nrownames(hap_block_all) <- as.character(1:n_total)\nG_mh_full <- build_G_mh(\n  mh_list = hap_block_all,\n  ref_mh  = hap_block_all[idx_train, ],\n  ids     = as.character(1:n_total)\n)\ntrain_ids_ch <- as.character(idx_train)\ntest_ids_ch  <- as.character(idx_test)\n\nrun_gblup_scenario <- function(sc, marker_label, G_full, y_tr, y_te, g_te,\n                                trait_type = \"continuous\") {\n  G_tr <- G_full[train_ids_ch, train_ids_ch]\n  y_named <- setNames(y_tr, train_ids_ch)\n  fit <- tryCatch(\n    masreml(y = y_named, G = list(g = G_tr),\n            trait = trait_type, method = \"auto\"),\n    error = function(e) NULL\n  )\n  if (is.null(fit)) {\n    return(data.frame(Trait=trait_type, Marker=marker_label, Model=\"GBLUP\",\n                      Status=\"ERROR\", r_train=NA, r_test_y=NA, r_test_g=NA,\n                      bias=NA, h2_post=NA, AUC=NA, p=NA, stringsAsFactors=FALSE))\n  }\n  pred <- predict(fit, G_full = list(g = G_full),\n                  train_ids = train_ids_ch, test_ids = test_ids_ch)\n  gebv_tr  <- fit$total_gebv + fit$fixed_effects[1]\n  gebv_te  <- pred$GEBV      + fit$fixed_effects[1]\n  h2_post  <- as.numeric(fit$varcomp$h2[\"g\"])\n  ev <- evaluate_prediction(\n          gebv        = gebv_te,\n          y           = y_te,\n          h2          = h2_post,\n          tbv         = g_te,\n          fitted_prob = if (trait_type == \"binary\") pred$prob else NULL\n        )\n  r_train  <- cor(gebv_tr, y_tr)\n  data.frame(Trait=trait_type, Marker=marker_label, Model=\"GBLUP\",\n             Status=\"OK\",\n             r_train=round(r_train,3), r_test_y=ev$r_test_y,\n             r_test_g=ev$r_test_g, bias=round(ev$bias,3),\n             h2_post=round(h2_post,3), AUC=ev$AUC,\n             p=nrow(G_tr), stringsAsFactors=FALSE)\n}\n\ngblup_results <- list()\nfor (sc_name in c(\"QTL@SNP\", \"QTL@MH\")) {\n  sc   <- if (sc_name == \"QTL@SNP\") sc_snp else sc_mh\n  g_te <- sc$g[idx_test]\n  for (trait in c(\"continuous\", \"binary\")) {\n    y_tr <- if (trait == \"binary\") sc$y_bin[idx_train] else sc$y_cont[idx_train]\n    y_te <- if (trait == \"binary\") sc$y_bin[idx_test]  else sc$y_cont[idx_test]\n    r_snp <- run_gblup_scenario(sc, \"SNP\", G_snp_full, y_tr, y_te, g_te, trait)\n    r_mh  <- run_gblup_scenario(sc, \"MH\",  G_mh_full,  y_tr, y_te, g_te, trait)\n    r_snp$Scenario <- r_mh$Scenario <- sc_name\n    gblup_results[[paste(sc_name, trait)]] <- rbind(r_snp, r_mh)\n  }\n}\ngblup_final <- do.call(rbind, gblup_results)\ngblup_final <- gblup_final[, c(\"Scenario\",\"Trait\",\"Marker\",\"Model\",\n                                \"r_train\",\"r_test_y\",\"r_test_g\",\n                                \"bias\",\"h2_post\",\"AUC\",\"p\",\"Status\")]\n\n# ── 7c. GWABLUP via masreml ──────────────────────────────────────────────────\nrun_gwablup_scenario <- function(sc, marker_type, y_tr, y_te, g_te,\n                                  G_full, geno_train, geno_all,\n                                  trait_type = \"continuous\") {\n  train_ids <- train_ids_ch\n  test_ids  <- test_ids_ch\n  y_named   <- setNames(y_tr, train_ids)\n  G_tr      <- G_full[train_ids, train_ids]\n  comp_name <- if (marker_type == \"SNP\") \"snp_add\" else \"mh_add\"\n\n  result <- tryCatch({\n    fit_tr <- masreml(y = y_named, G = list(g = G_tr),\n                      trait = trait_type, method = \"auto\")\n    if (marker_type == \"SNP\") {\n      markers_tr  <- list(snp_add = geno_train)\n      ref_markers <- list(snp_add = geno_train)\n    } else {\n      hap_tr      <- hap_block_all[idx_train, ]\n      rownames(hap_tr) <- train_ids\n      markers_tr  <- list(mh_add = hap_tr)\n      ref_markers <- list(mh_add = hap_tr)\n    }\n    gwas_tr <- run_gwas(\n      markers     = markers_tr,\n      y           = y_named,\n      masreml_fit = fit_tr,\n      ref_markers = ref_markers\n    )\n    fit_wa <- gwablup(\n      y           = y_named,\n      markers     = markers_tr,\n      gwas_result = gwas_tr,\n      trait       = trait_type,\n      ref_markers = ref_markers\n    )\n    g_full_named        <- list(G_full)\n    names(g_full_named) <- comp_name\n    pred <- predict(fit_wa,\n                    G_full    = g_full_named,\n                    train_ids = train_ids,\n                    test_ids  = test_ids)\n    gebv_tr <- fit_wa$total_gebv + fit_wa$fixed_effects[1]\n    gebv_te <- pred$GEBV         + fit_wa$fixed_effects[1]\n    h2_post <- as.numeric(fit_wa$varcomp$h2[comp_name])\n    ev <- evaluate_prediction(\n            gebv        = gebv_te,\n            y           = y_te,\n            h2          = h2_post,\n            tbv         = g_te,\n            fitted_prob = if (trait_type == \"binary\") pred$prob else NULL\n          )\n    list(status=\"OK\",\n         r_train  = round(cor(gebv_tr, y_tr), 3),\n         r_test_y = ev$r_test_y,\n         r_test_g = ev$r_test_g,\n         bias     = ev$bias,\n         h2_post  = round(h2_post, 3),\n         auc      = ev$AUC,\n         p        = length(fit_wa$total_gebv))\n  }, error = function(e)\n    list(status=paste(\"ERROR:\", conditionMessage(e)),\n         r_train=NA, r_test_y=NA, r_test_g=NA,\n         bias=NA, h2_post=NA, auc=NA, p=NA))\n\n  data.frame(Trait=trait_type, Marker=marker_type, Model=\"GWABLUP\",\n             Status=result$status,\n             r_train=result$r_train, r_test_y=result$r_test_y,\n             r_test_g=result$r_test_g, bias=result$bias,\n             h2_post=result$h2_post, AUC=result$auc,\n             p=result$p, stringsAsFactors=FALSE)\n}\n\ngeno_train <- geno_snp_all[idx_train, ]\nrownames(geno_train) <- train_ids_ch\nstorage.mode(geno_train) <- \"double\"\n\ngwablup_results <- list()\nfor (sc_name in c(\"QTL@SNP\", \"QTL@MH\")) {\n  sc   <- if (sc_name == \"QTL@SNP\") sc_snp else sc_mh\n  g_te <- sc$g[idx_test]\n  for (trait in c(\"continuous\", \"binary\")) {\n    y_tr <- if (trait == \"binary\") sc$y_bin[idx_train] else sc$y_cont[idx_train]\n    y_te <- if (trait == \"binary\") sc$y_bin[idx_test]  else sc$y_cont[idx_test]\n    r_snp <- run_gwablup_scenario(sc, \"SNP\", y_tr, y_te, g_te,\n                                   G_snp_full, geno_train, geno_snp_all, trait)\n    r_mh  <- run_gwablup_scenario(sc, \"MH\",  y_tr, y_te, g_te,\n                                   G_mh_full,  geno_train, geno_snp_all, trait)\n    r_snp$Scenario <- r_mh$Scenario <- sc_name\n    gwablup_results[[paste(sc_name, trait)]] <- rbind(r_snp, r_mh)\n  }\n}\ngwablup_final <- do.call(rbind, gwablup_results)\ngwablup_final <- gwablup_final[, c(\"Scenario\",\"Trait\",\"Marker\",\"Model\",\n                                    \"r_train\",\"r_test_y\",\"r_test_g\",\n                                    \"bias\",\"h2_post\",\"AUC\",\"p\",\"Status\")]\n\n# ── 8. Run all Bayesian combinations ─────────────────────────────────────────\nall_results <- list()\nfor (sc_name in c(\"QTL@SNP\", \"QTL@MH\")) {\n  sc   <- if (sc_name == \"QTL@SNP\") sc_snp else sc_mh\n  g_te <- sc$g[idx_test]\n  for (trait in c(\"continuous\", \"binary\")) {\n    y_tr_use <- if (trait == \"binary\") sc$y_bin[idx_train] else sc$y_cont[idx_train]\n    y_te_use <- if (trait == \"binary\") sc$y_bin[idx_test]  else sc$y_cont[idx_test]\n    r_mh  <- run_scenario(sc, W_mh_train, W_mh_test,\n                          y_tr_use, y_te_use,\n                          g_te, \"MH\", trait)\n    r_snp <- run_scenario(sc, W_snp_train, W_snp_test,\n                          y_tr_use, y_te_use,\n                          g_te, \"SNP\", trait)\n    res        <- rbind(r_mh, r_snp)\n    res$Scenario <- sc_name\n    all_results[[paste(sc_name, trait)]] <- res\n  }\n}\n\n# ── 9. Combined results ──────────────────────────────────────────────────────\nfinal <- rbind(do.call(rbind, all_results), gblup_final, gwablup_final)\nfinal <- final[, c(\"Scenario\",\"Trait\",\"Marker\",\"Model\",\n                   \"r_train\",\"r_test_y\",\"r_test_g\",\n                   \"bias\",\"h2_post\",\"AUC\",\"p\",\"Status\")]\nfinal <- final[order(final$Scenario, final$Trait, final$Marker, final$Model), ]\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Combined results: 2 QTL scenarios × 2 traits × 2 markers × 4 models = 32 model fits. Train n = 200, test n = 100, h² target = 0.3, n_QTL = 10.\n\n|Scenario |Trait      |Marker |Model   | r_train| r_test_y| r_test_g|  bias| h2_post|   AUC|   p|Status |\n|:--------|:----------|:------|:-------|-------:|--------:|--------:|-----:|-------:|-----:|---:|:------|\n|QTL@MH   |binary     |MH     |BayesA  |   0.898|    0.295|    0.726| 0.595|   0.366| 0.671| 150|OK     |\n|QTL@MH   |binary     |MH     |BayesR  |   0.919|    0.314|    0.758| 0.514|   0.506| 0.680| 150|OK     |\n|QTL@MH   |binary     |MH     |GBLUP   |   0.744|    0.128|    0.573| 1.466|   0.182| 0.568| 200|OK     |\n|QTL@MH   |binary     |MH     |GWABLUP |   0.744|    0.128|    0.572| 1.460|   0.182| 0.571| 200|OK     |\n|QTL@MH   |binary     |SNP    |BayesA  |   0.841|    0.178|    0.521| 0.435|   0.277| 0.592| 100|OK     |\n|QTL@MH   |binary     |SNP    |BayesR  |   0.803|    0.191|    0.535| 0.539|   0.215| 0.603| 100|OK     |\n|QTL@MH   |binary     |SNP    |GBLUP   |   0.686|    0.164|    0.497| 1.943|   0.182| 0.600| 200|OK     |\n|QTL@MH   |binary     |SNP    |GWABLUP |   0.687|    0.165|    0.498| 1.946|   0.182| 0.599| 200|OK     |\n|QTL@MH   |continuous |MH     |BayesA  |   0.785|    0.442|    0.800| 1.064|   0.203|    NA| 150|OK     |\n|QTL@MH   |continuous |MH     |BayesR  |   0.787|    0.459|    0.832| 0.856|   0.293|    NA| 150|OK     |\n|QTL@MH   |continuous |MH     |GBLUP   |   0.817|    0.290|    0.696| 1.337|   0.365|    NA| 200|OK     |\n|QTL@MH   |continuous |MH     |GWABLUP |   0.754|    0.270|    0.682| 1.524|   0.290|    NA| 200|OK     |\n|QTL@MH   |continuous |SNP    |BayesA  |   0.751|    0.261|    0.530| 0.737|   0.186|    NA| 100|OK     |\n|QTL@MH   |continuous |SNP    |BayesR  |   0.739|    0.264|    0.538| 0.638|   0.225|    NA| 100|OK     |\n|QTL@MH   |continuous |SNP    |GBLUP   |   0.769|    0.233|    0.525| 1.186|   0.326|    NA| 200|OK     |\n|QTL@MH   |continuous |SNP    |GWABLUP |   0.776|    0.232|    0.524| 1.084|   0.345|    NA| 200|OK     |\n|QTL@SNP  |binary     |MH     |BayesA  |   0.875|    0.338|    0.560| 0.688|   0.347| 0.680| 150|OK     |\n|QTL@SNP  |binary     |MH     |BayesR  |   0.851|    0.339|    0.629| 0.713|   0.321| 0.678| 150|OK     |\n|QTL@SNP  |binary     |MH     |GBLUP   |   0.725|    0.290|    0.444| 3.244|   0.182| 0.657| 200|OK     |\n|QTL@SNP  |binary     |MH     |GWABLUP |   0.724|    0.289|    0.447| 3.204|   0.182| 0.657| 200|OK     |\n|QTL@SNP  |binary     |SNP    |BayesA  |   0.866|    0.439|    0.797| 0.892|   0.383| 0.752| 100|OK     |\n|QTL@SNP  |binary     |SNP    |BayesR  |   0.831|    0.461|    0.897| 0.873|   0.376| 0.766| 100|OK     |\n|QTL@SNP  |binary     |SNP    |GBLUP   |   0.708|    0.360|    0.622| 4.038|   0.182| 0.726| 200|OK     |\n|QTL@SNP  |binary     |SNP    |GWABLUP |   0.709|    0.362|    0.626| 4.027|   0.182| 0.726| 200|OK     |\n|QTL@SNP  |continuous |MH     |BayesA  |   0.774|    0.480|    0.832| 1.146|   0.232|    NA| 150|OK     |\n|QTL@SNP  |continuous |MH     |BayesR  |   0.714|    0.533|    0.939| 0.936|   0.303|    NA| 150|OK     |\n|QTL@SNP  |continuous |MH     |GBLUP   |   0.762|    0.392|    0.601| 2.696|   0.265|    NA| 200|OK     |\n|QTL@SNP  |continuous |MH     |GWABLUP |   0.708|    0.314|    0.518| 2.882|   0.214|    NA| 200|OK     |\n|QTL@SNP  |continuous |SNP    |BayesA  |   0.756|    0.562|    0.931| 1.008|   0.336|    NA| 100|OK     |\n|QTL@SNP  |continuous |SNP    |BayesR  |   0.676|    0.565|    0.973| 0.951|   0.318|    NA| 100|OK     |\n|QTL@SNP  |continuous |SNP    |GBLUP   |   0.770|    0.499|    0.766| 2.303|   0.336|    NA| 200|OK     |\n|QTL@SNP  |continuous |SNP    |GWABLUP |   0.769|    0.531|    0.817| 2.182|   0.337|    NA| 200|OK     |\n\n\n:::\n:::\n\n\n## Analysis\n\nSimulation results support the theory of marker-QTL unit congruence. When the QTL is a combined effect of microhaplotype blocks, the accuracy of microhaplotype-based BayesR prediction reaches 0.832 for continuous traits and 0.758 for binary traits, which is 20-30% higher than that of SNPs.  This phenomenon shows that when the QTL is a combined effect of multiple microhaplotype blocks, SNPs cannot capture the QTL signal, as it disperses across all blocks.\n\nWhen the QTL is only a single independent SNP variant, the prediction accuracy of SNP-based BayesR reaches 0.973 for continuous traits and 0.897 for binary traits. Interestingly, although SNPs appear superior in this scenario, microhaplotypes remain quite competitive, with a smaller accuracy gap for continuous traits. This phenomenon shows that microhaplotypes can still capture the QTL signal, even though the QTL is composed of independent SNPs. \n\nIn both scenarios, the Bayesian models (BayesR and BayesA) outperform GBLUP and GWABLUP in bias calibration. GBLUP exhibits severe bias inflation, with values ​​exceeding 2.0 to 4.0 under QTL@SNP, as variance is spread uniformly across all markers rather than concentrated at the true QTL. BayesR has more calibrated predictions (bias approaching 1.0) than BayesA, due to its mixture priors that more aggressively downscale non-QTL markers toward zero. GWABLUP offers only marginal improvement over GBLUP, with the GWAS weighting step insufficient to recover the rare QTL signal captured by the full mixture prior.\n\nIndeed, the dataset is small, which may not fully explain the theory, so further investigation with a larger dataset or even the real on is crucial.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}