---
title: "Build SNP Dominance Relationship Matrix"
---

## Build SNP Dominance Relationship Matrix {.unnumbered}


### Description

Constructs the SNP dominance relationship matrix (D) following
Da (2015). Captures non-additive (dominance) genetic
relationships among individuals. Can be used alongside the additive
G matrix in <code>masreml()</code> to partition genetic variance into
additive and dominance components.



### Usage

<pre><code class='language-R'>build_D_snp(W)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="W">W</code></td>
<td>
numeric matrix (n x m) of raw genotype codes, where n is the
number of individuals and m is the number of SNP markers. Values must
be 0, 1, or 2. Same format as <code>build_G_snp</code>.
</td></tr>
</table>


### Details

<strong>SNP dominance GRM (Da, 2015).</strong>
For individual $i$ at SNP $j$ with allele frequency $p_j$
and $q_j = 1 - p_j$, the dominance-coded value is:


<dl>
<dt>Genotype $aa$ (dosage = 0):</dt><dd>$W_{D,ij} = -2p_j^2$
</dd>
<dt>Genotype $Aa$ (dosage = 1):</dt><dd>$W_{D,ij} = 2p_j q_j$
</dd>
<dt>Genotype $AA$ (dosage = 2):</dt><dd>$W_{D,ij} = -2q_j^2$
</dd>
</dl>

The dominance GRM is then:

<p style="text-align: center;">$D = \frac{W_D W_D^\top}{\sum_j (2p_j q_j)^2}$




### Value

numeric matrix (n x n) of dominance relationships.



### References

Da, Y. (2015) Multi-allelic haplotype model based on genetic partition for
genomic prediction and variance component estimation using SNP markers.
<em>BMC Genetics</em> 16:144. [doi:10.1186/s12863-015-0301-1](https://doi.org/10.1186/s12863-015-0301-1)



### See Also

<code>build_G_snp</code>, <code>masreml</code>



### Examples
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library("masreml")

d <- load_data("small")
D <- build_D_snp(d$snp)
dim(D)
# Off-diagonal mean ~ 0 under random mating; diagonal carries the
# dominance "self" contributions.
round(summary(diag(D)), 3)




```
