---
title: "Build Pedigree-Based Additive Relationship Matrix"
---

## Build Pedigree-Based Additive Relationship Matrix {.unnumbered}


### Description

Constructs the numerator relationship matrix (A) from pedigree data
following Henderson (1976). The A matrix captures additive genetic
relationships based on known ancestry, and can be used in
<code>masreml()</code> for pedigree-based BLUP (PBLUP) or combined with
genomic relationship matrices.



### Usage

<pre><code class='language-R'>build_A_ped(pedigree)
</code></pre>


### Arguments

<table>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="pedigree">pedigree</code></td>
<td>
data.frame with columns <code>id</code>, <code>sire</code>,
and <code>dam</code>. Rows must be ordered such that parents appear
before offspring. IDs must be integers or convertible to integer
(1-based). Use 0 for unknown parents. Example format:

<pre>
  id sire dam
   1    0   0
   2    0   0
   3    1   2
   4    1   2
   5    3   4
  </pre></td></tr>
</table>


### Value

numeric matrix (n x n) of additive relationships. Diagonal
elements equal 1 + inbreeding coefficient. Off-diagonal elements
equal twice the coefficient of kinship between pairs.



### References

Henderson (1976) A simple method for computing the inverse of a
numerator relationship matrix. <em>Biometrics</em> 32:69-83.



### See Also

<code>build_G_snp</code>, <code>masreml</code>



### Examples
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library("masreml")

# build_A_ped() expects integer indices: id = 1..n, sire/dam = integers
# into id (0 = unknown founder). The bundled pedigree uses character IDs
# with NA for founder parents, so we convert before calling.
d      <- load_data("small")
ped    <- d$pedigree
id_map <- setNames(seq_along(ped$id), ped$id)
ped_int <- data.frame(
  id   = id_map[ped$id],
  sire = ifelse(is.na(ped$sire), 0L, id_map[ped$sire]),
  dam  = ifelse(is.na(ped$dam),  0L, id_map[ped$dam])
)
A <- build_A_ped(ped_int)
dim(A)
# Diagonal ~ 1 + inbreeding coefficient
round(summary(diag(A)), 3)




```
